### ISSUE TITLE
Where Should I Put Extension Project Folder To Run This In My VS Code?

### ISSUE THREAD

**Issue by harshilpatel984** [microsoft/BCTech#4]
Hi,
Where should i put this project folder to run this VS Code extension in my VS Code.
Please give me the path for this.

**Comment by harshilpatel984** [comment]
I have put this translation file project on the location:
C:\Users\harshil.p\.vscode\extensions\TranslateXLIFF

now i get the command in the command palate but
it gives an error like this:
command 'extension.translatexliff' not found

**Comment by staedter** [comment]
I have a similiar Issue ... building the Extenstion works and it opens a new VSCode Windows with the extension installed. But the packaged .vsix (created with vsce package) gives me the same error "command 'extension.translatexliff' not found"...

**Comment by VincentNic** [comment]
Do you get the translation command to work when you deploy directly from VS code with CTRL+F5?

**Comment by staedter** [comment]
Yes. When I build it from VS Code it works. But the packaged .vsix does not.

**Comment by VincentNic** [comment]
I could repro the issue. There was some missing dependencie in the app.json. It should be fixed with the pr #12. 
Thanks for reporting this.

**Comment by staedter** [comment]
Thanks alot.

Unfortunately that did not yet solve it for me. I pulled the latest version and rebuild and packaged it again. but when I install the .vsix I still get the command not found error.

I will investigate further tomorrow.

ps. you had one trailing comma in line 37 of the package.json

**Comment by staedter** [comment]
Ah nevermind. I apparently had to manually delete the already installed version from the %userprofile%\.vscode\extension folder and reinstall the new package...

The extension is working, now I only have to figure out how the rest of you Demo worked xD.

Issue is closed for me :)

**Comment by VincentNic** [comment]
Great. Let me know if you have more question or issues.

**Comment by miljance** [comment]
Hi,

In my case it also does not work when published from VSCode with F5 or Ctrl+F5.  I get the same Erro

Did the dependencies change in the meanwhile?

![image](https://user-images.githubusercontent.com/42636293/98855093-c3c4a380-245b-11eb-97ab-74f67bea1227.png)
